export const ADD_LIST = "ADD_LIST";
// export const ADD_PRODUCT_TO_SHOPPING_LIST = "ADD_PRODUCT_TO_SHOPPING_LIST";
// export const CUSTOMIZE_LIST = "CUSTOMIZE_LIST";
export const REMOVE_LIST = "REMOVE_LIST";
// export const TOGGLE_LIST = "TOGGLE_LIST";
//export const INCREMENT_NUM_OF_PRODUCTS = "INCREMENT_NUM_OF_PRODUCTS";
//export const DECREMENT_NUM_OF_PRODUCTS = "DECREMENT_NUM_OF_PRODUCTS";

