export const ADD_LIST = "ADD_LIST";
export const ADD_PRODUCT_TO_SHOPPING_LIST = "ADD_PRODUCT_TO_SHOPPING_LIST";
export const CUSTOMIZE_LIST = "CUSTOMIZE_LIST";
export const TOGGLE_LIST = "TOGGLE_LIST";
